config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # resources :users
  get '/users/:id', to: 'users#show', as: 'user'
  root 'activities#index'
  resources :knowledges
  resources :activities do
    get :autocomplete_approved_knowledge_name, on: :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :authentication_keys => [:login] # , :validatable
  has_many :activities
  has_paper_trail
  before_create :default_role
  validates :username, uniqueness: { case_sensitive: false }

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

   def self.find_first_by_auth_conditions(warden_conditions)
     conditions = warden_conditions.dup
     if login = conditions.delete(:login)
       where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
     else
       where(conditions).first
     end
   end

  private

  def default_role
    self.role = 'user'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_activities = @user.activities.last(10)
  end
end

app/views/users/_sidebar.html.erb
<div class="sidebar">
  <h2><%= @user.login %></h2>
  <div class="avatar">
    <%= gravatar_for @user, size: 150 %>
  </div>
  <div class="info">
    Дата регистрации: <%= nice_russian_date(@user.created_at) %>
    <br>
    Последний вход: <%= nice_russian_date(@user.last_sign_in_at) %>
  </div>
</div>

app/views/users/show.html.slim
h3 Последние изученные материалы
.activity-day.cleaftix
  - @user_activities.each do |activity|
    .activity-point
      h4= link_to knowledge_path(activity.knowledge) do
        = activity.name
        '
        small= nice_russian_date(activity.created_at)
      .comment
        = truncate(activity.comment, length: 255, separator: ' ', omission: '...')
    hr

- content_for :sidebar do
  = render 'users/sidebar'