config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # resources :users
  get '/users/:id', to: 'users#show', as: 'user'
  root 'activities#index'
  resources :knowledges
  resources :activities do
    get :autocomplete_approved_knowledge_name, on: :collection
  end

end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
  KINDS = %w(Книга Скринкаст Видео Курс).freeze
  validates :name, :kind, presence: true
  validates :kind, inclusion: { in: KINDS }
  has_paper_trail
  has_many :activities
  acts_as_taggable

  scope :approved, -> { where(approved: true) }
end

app/controllers/knowledges_controller.rb
class KnowledgesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :update, :edit]

  def index
    @knowledges = Knowledge.approved.order(created_at: :desc)
      .paginate(page: params[:page], per_page: 12)
  end

  def show
    @knowledge = Knowledge.find(params[:id])
    @learned = @knowledge.activities.count
  end

  def edit
    @knowledge = Knowledge.find(params[:id])
    authorize! :edit, @knowledge, message: 'Доступно только администратору.'
  end

  def update
    @knowledge = Knowledge.find(params[:id])
    authorize! :update, @knowledge, message: 'Доступно только администратору.'
    if @knowledge.update(knowledge_params)
      redirect_to @knowledge, notice: 'Зание успешно обновлено'
    else
      render :edit
    end
  end

  def new
    @knowledge = Knowledge.new
    authorize! :new, @knowledge, message: 'Доступно только зарегистрированным.'
  end

  def create
    @knowledge = Knowledge.new(knowledge_params)
    authorize! :create, @knowledge, message: 'Доступно только зарегистрированным.'
    if @knowledge.save
      redirect_to @knowledge, notice: 'Знание успешно добавлено'
    else
      render :new
    end
  end

  def destroy
    @knowledge = Knowledge.find(params[:id])
    authorize! :destroy, @knowledge, message: 'Доступно только администратору.'
    @knowledge.destroy
    redirect_to knowledges_path, notice: 'Знание удалено'
  end

  private

  def knowledge_params
    params.require(:knowledge).permit(:name, :description, :link, :kind,
                                      :approved, :tag_list)
  end
end

app/helpers/knowledge_helper.rb
module KnowledgeHelper

  def card_bg_color(kind)
    if kind == 'Книга'
      'book'
    elsif kind == 'Скринкаст'
      'screencast'
    elsif kind == 'Статья'
      'article'
    else
      'tutorial'
    end
  end

  def card_icon(kind)
    if kind == 'Книга'
      '<i class="fa fa-book fa-5x"></i>'.html_safe
    elsif kind == 'Скринкаст'
      '<i class="fa fa-youtube-play fa-5x"></i>'.html_safe
    elsif kind == 'Статья'
      '<i class="fa fa-file-text fa-5x"></i>'.html_safe
    else
      '<i class="fa fa-file-code-o fa-5x"></i>'.html_safe
    end
  end
end

app/views/knowledges/_form.html.erb
<%= simple_form_for knowledge do |f| %>
  <%= f.input :name, label: "Название", class: "form-control" %>
  <%= f.input :kind, collection: Knowledge::KINDS, selected: "Книга", label: "Вид" %>
  <%= f.input :link, label: "Ссылка", class: "form-control" %>
  <%= f.input :description, label: "Описание", class: "form-control" %>
  <%= f.input :tag_list, label: 'Список подходящих тем' %>
  <% if current_user && current_user.role == "admin" %>
    <%= f.input :approved, label: 'Одобрено?', class: 'form-control' %>
  <% end %>
  <br>
  <%= f.button :submit, value: 'Сохранить знание', class: "btn btn-success" %>
<% end %>

app/views/knowledges/edit.html.erb
<h3>Редактирование <%= @knowledge.name %></h3>

<%= render 'form', knowledge: @knowledge %>

app/views/knowledges/index.html.erb
<p>
  <%= link_to 'Добавить знание', new_knowledge_path, class: "btn btn-success" %>
</p>

<div class="list">
<% @knowledges.each do |knowledge| %>
<div class="col-xl-4 col-md-4 col-sm-6 col-xs-12">
  <div class="knowledge-card <%= card_bg_color(knowledge.kind) %>">
  <div class="cover">
    <div class="icon">
      <%= card_icon(knowledge.kind) %>
    </div>
  </div>
  <div class="content">
    <div class="title">
      <h4><%= link_to truncate(knowledge.name, length: 45, separator: ' '), knowledge %></h4>
    </div>
    <p><%= truncate(knowledge.description, length: 100, separator: ' ') %></p>
  </div>
  </div>
</div>
<% end %>
</div>

<%= will_paginate @knowledges %>

app/views/knowledges/new.html.erb
<h3>Новое знание</h3>

<%= render 'form', knowledge: @knowledge %>

app/views/knowledges/show.html.erb
<div class="knowledge">
  <!-- <div class="cover"> -->
  <!-- </div> -->
  <h2><%= @knowledge.name %>
  <% if can? :update, Knowledge %>
    <small>
    <%= link_to edit_activity_path(@knowledge) do %>
      <i class="fa fa-edit"></i>
    <% end %>
    </small>
  <% end %>
  <% if can? :update, Knowledge %>
    <small>
    <%= link_to @knowledge, method: :delete, data: {confirm: "Вы уверены?"} do %>
      <i class="fa fa-remove"></i>
    <% end %>
    </small>
  <% end %>
  </h2>
  <% if @learned > 0 %>
  Уже <strong><%= @learned %></strong> человек изучили это.
  <% else %>
  Еще никто не изучил этот материал.
  <% end %>

  <% if can? :manage, Knowledge %>
    <small>
    <%= link_to 'Редактировать', rails_admin.edit_path('knowledge', @knowledge) %>
    </small>
    <br>
  <% end %>

<% if @knowledge.link? %>
  <strong>Сайт:</strong> <%= @knowledge.link %>
<% end %>
  <div class="description">
    <%= @knowledge.description %>
  </div>
</div>
<hr>

<div class="opinions">
<% @knowledge.activities.each do |activity| %>

<div class="col-md-1">
  <%= link_to activity.user do %>
    <%= gravatar_for activity.user, size: 50 %>
  <% end %>
</div>

<div class="col-md-11">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title"><span class="user"><%= link_to activity.user.try(:login), user_path(activity.user_id.to_i) %></span>:
        <%= nice_russian_date(activity.created_at) %>
      </h4>
    </div>
    <div class="panel-body comment">
      <%= activity.comment %>
    </div>
  </div>
</div>

<% end %>
</div>