config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # resources :users
  get '/users/:id', to: 'users#show', as: 'user'
  root 'activities#index'
  resources :knowledges
  resources :activities do
    get :autocomplete_approved_knowledge_name, on: :collection
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :kind, inclusion: { in: Knowledge::KINDS }
  validates :name, :comment, :kind, presence: true
  has_paper_trail
  belongs_to :user
  belongs_to :knowledge
  before_create :create_knowledge
  acts_as_taggable

  scope :created_on, ->(date) { where(created_at: date.beginning_of_day..date.end_of_day) }

  private

  def create_knowledge
    unless Knowledge.exists?(name: self.name)
    logger.info "#{self.name} knowledge was created"
      Knowledge.create!(name: self.name, kind: self.kind,
                        tag_list: self.tag_list)
    end
  end
end

app/controllers/activities_controller.rb
# Контроллер активностей
class ActivitiesController < ApplicationController
  autocomplete :approved_knowledge, :name, full: true, extra_data: [:link]
  load_and_authorize_resource except: [:index, :show]

  def index
    if current_user
      @activities = Activity.all.order(created_at: :desc)
        .group_by { |d| d.created_at.beginning_of_day }
      @activities_keys = @activities.keys.paginate(page: params[:page], per_page: 7)
    end
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = current_user.activities.build(activity_params)

    if @activity.save
      unless @activity.knowledge_id
        @activity.update_attribute(:knowledge, Knowledge.find_by(name: activity_params[:name]))
        # @activity.knowledge_id = Knowledge.find_by(name: activity_params[:name]).id
        @activity.save
      end
      redirect_to @activity, notice: 'Активность создана'
    else
      render :new
    end
  end

  def edit
    @activity = user_activity
  end

  def update
    @activity = user_activity
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Активность обновлена'
    else
      render :edit, notice: 'Исправьте ошибки'
    end
  end

  def destroy
    @activity = user_activity
    @activity.destroy
    redirect_to root_path, notice: 'Активность удалена'

  end

  def show
    @activity = user_activity
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :comment, :link, :time_spent, :kind,
                                     :knowledge_id, :tag_list)
  end

  def user_activity
    current_user.activities.find(params[:id])
  end
end

app/views/activities/_form.html.slim
= simple_form_for activity do |f|
  = f.input :name, label: 'Что вы изучили?', class: 'form-control', url: autocomplete_approved_knowledge_name_activities_path, as: :autocomplete, update_elements: { link: '#activity_link', id: '#activity_knowledge_id'}
  = f.input :kind, collection: Knowledge::KINDS, selected: "Книга", label: "Вид"
  = f.input :comment, label: 'Комментарий к изученному'
  = f.input :link, label: 'Ссылка на изученный материал'
  = f.input :time_spent, label: 'Сколько затрачено времени?'
  = f.input :tag_list, label: 'Список подходящих тем'
  = f.input :knowledge_id, as: :hidden

  br
  = f.button :submit, value: 'Сохранить активность', class: "btn btn-success"

app/views/activities/edit.html.slim
h3 Редактирование активности
= render 'form', activity: @activity

app/views/activities/index.html.slim
- if current_user
  = link_to 'Добавить активность', new_activity_path, class: "btn btn-primary center-block"

  - @activities_keys.each do |date|
    h3= nice_russian_date date
    - Activity.created_on(date).each do |activity|
      .activity-day.clearfix
        .activity-point
          .col-md-1
            = link_to activity.user do
              = gravatar_for activity.user, size: 50

          .col-md-11
            .panel.panel-default
              .panel-heading
                h4.panel-title
                  span.user= link_to activity.user.try(:login), user_path(activity.user_id)
                  ' :
                  = link_to activity.name, activity
              .panel-body.comment
                = truncate(activity.comment, length: 120, separator: ' ', omission: '...')

    hr

  = will_paginate @activities_keys

app/views/activities/new.html.slim
h3 Новая активность
= render 'form', activity: @activity

app/views/activities/show.html.erb
<div class="activity">
  <div class="cover">
    <img src="http://lorempixel.com/200/300/" alt="">
  </div>
  <h2><%= @activity.name %>
  <% if can? :update, Activity %>
    <small>
    <%= link_to edit_activity_path(@activity) do %>
      <i class="fa fa-edit"></i>
    <% end %>
    </small>
  <% end %>
  <% if can? :update, Activity %>
    <small>
    <%= link_to @activity, method: :delete, data: {confirm: "Вы уверены?"} do %>
      <i class="fa fa-remove"></i>
    <% end %>
    </small>
  <% end %>
  </h2>
  <div class="local-link">
  <% if @activity.knowledge %>
    Ссылка на сайте: <%= link_to @activity.knowledge.name, @activity.knowledge %>
  <% end %>
  </div>

<div class="opinions">
  <div class="media">
    <div class="media-body">
          <small><%= nice_russian_date(@activity.created_at) %></small>
      <p><%= @activity.comment %></p>
    </div>
  </div>

</div>

</div>
<hr>