config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # resources :users
  get '/users/:id', to: 'users#show', as: 'user'
  root 'activities#index'
  resources :knowledges
  resources :activities do
    get :autocomplete_approved_knowledge_name, on: :collection
  end

end

app/views/layouts/_header.html.erb
<nav class="mui" role="navigation">
  <div class="container">
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png' %>
      Learn Track
    <% end %>
  </div>
    <ul class="navigation">
      <li><%= link_to "Знания", knowledges_path %></li>
      <li><%= link_to 'Активность', activities_path %></li>
    </ul>
    <ul class="navigation navbar-right">
      <% unless current_user %>
        <li><%= link_to new_user_session_path, class: 'btn btn-primary mui-blue' do %>
        <span class="glyphicon glyphicon-user"></span>
        Войти
        <% end %>
        </li>
        <li><%= link_to 'Регистрация', new_user_registration_path, class: 'btn btn-primary mui-blue' %></li>
      <% else %>
        <li class="dropdown">
        <div class="btn-group">
          <button type="button" class="btn btn-default mui-blue"><%= gravatar_for current_user, size: 15 %><%= link_to current_user.login, current_user %></button>
          <button type="button" class="btn btn-default mui-blue dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
            <span class="sr-only">Показать меню</span>
          </button>
          <ul class="dropdown-menu mui-dropdown" role="menu">
            <li class="divider"></li>
            <li><%= link_to "Настройки", edit_user_registration_path %></li>
            <li><%= link_to "Выход", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <% if current_user %>
  <h4>Недавно изученное:</h4>
  <% #отрефакторить в хелпер %>
  <ol>
    <% @last_activities = current_user.activities.last(5) %>
    <% @last_activities.each do |activity| %>
    <li><%= link_to activity.name, activity %></li>
    <% end %>
  </ol>

  Всего вами изучено <%= current_user.activities.count %> материалов.
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnTrack</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,500,300,300italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<div class="container">
<%= render partial: "shared/flash_messages", flash: flash %>
<div class="col-xl-9 col-md-9 col-sm-8 col-xs-12">
  <%= yield %>
</div>
<div class="col-xl-3 col-md-3 col-sm-4 col-xs-12">
<% if content_for?(:sidebar) %>
  <%= yield :sidebar %>
<% else %>
  <%= render 'layouts/sidebar' %>
<% end %>
</div>

</div>

</body>
</html>